# Generated by Django 5.1.3 on 2025-03-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=100)),
            ],
        ),
    ]
