# Generated by Django 5.1.3 on 2025-03-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_transactionnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_page_visits', models.PositiveIntegerField(default=0)),
                ('kokeb_calculator_visits', models.PositiveIntegerField(default=0)),
                ('calculators_list_visits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
