# Generated by Django 4.2.7 on 2026-07-12 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_sitestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionnumber',
            name='claimed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionnumber',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionnumber',
            name='transaction_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
