# Generated by Django 5.1.3 on 2025-01-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfname', models.CharField(max_length=50)),
                ('mothersname', models.CharField(max_length=50)),
                ('sign', models.CharField(max_length=20)),
            ],
        ),
    ]
