# Generated by Django 5.1.3 on 2025-01-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mothersname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='selfname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='sign',
            field=models.CharField(max_length=100),
        ),
    ]
