# Generated by Django 5.1.3 on 2025-02-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
