# Generated by Django 5.1.3 on 2025-03-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_After_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Transaction_Number', models.CharField(max_length=100)),
            ],
        ),
    ]
