# Generated by Django 5.1.3 on 2025-03-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_message_after_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_after_transaction',
            old_name='Transaction_Number',
            new_name='transaction_number',
        ),
    ]
