# Generated by Django 5.1.3 on 2025-03-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_rename_transaction_number_message_after_transaction_transaction_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_after_transaction',
            name='status',
            field=models.CharField(default='denied', max_length=100),
        ),
    ]
