# Generated by Django 4.2.7 on 2026-07-12 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0010_calculationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_text', models.TextField()),
                ('parsed_reference', models.CharField(blank=True, default='', max_length=64)),
                ('parsed_amount', models.CharField(blank=True, default='', max_length=32)),
                ('parsed_recipient', models.CharField(blank=True, default='', max_length=128)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('verification_checks', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('auto_approved', 'Auto approved'), ('manual_approved', 'Manual approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
